[project]
name = "eagleeye-object-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "opencv-python",
  "numpy",
  "pynetworktables",
  "ultralytics",
  "Flask",
  "numba",
  "tensorflow",
  "customtkinter",
  "torch",
  "tqdm",
  "pip",
  "pillow",
  "filelock",
  "clearml",
  "pygrabber",
  "comtypes",
  "imutils",
  "flask_socketio",
  "pupil-apriltags",
  "flask_cors",
  "memryx; sys_platform != 'win32'",
]

[tool.uv.sources]
memryx = { index = "memryx" }
torch = { index = "pytorch" }

[[tool.uv.index]]
name = "memryx"
url = "https://developer.memryx.com/pip"
explicit = true

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv]
required-environments = [
    "sys_platform == 'win32'",
    "sys_platform == 'linux'"
]