[project]
name = "eagleeye-object-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "opencv-python",
  "numpy",
  "pynetworktables",
  "ultralytics",
  "numba",
  "tensorflow",
  "customtkinter",
  "torch",
  "torchvision",
  "tqdm",
  "pip",
  "pillow",
  "filelock",
  "clearml",
  "pygrabber",
  "comtypes",
  "imutils",
  "pupil-apriltags",
  "flask",
  "flask-cors",
  "flask-socketio",
  "line_profiler",
  "onnxruntime",
  "linuxpy",
  "maturin",
  "pydantic",
  "mypy",
  "psutil",
  "memryx; sys_platform == 'linux'",
]

[tool.uv.sources]
memryx = { index = "memryx" }
torch = [
    { index = "pytorch-cuda", marker = "sys_platform == 'win32'" },
    { index = "pytorch-cpu", marker = "sys_platform == 'linux'"}
]
torchvision = [
    { index = "pytorch-cuda", marker = "sys_platform == 'win32'" },
    { index = "pytorch-cpu", marker = "sys_platform == 'linux'"}
]

[[tool.uv.index]]
name = "memryx"
url = "https://developer.memryx.com/pip"
explicit = true

[[tool.uv.index]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv]
required-environments = [
    "sys_platform == 'linux'"
]
