[project]
name = "eagleeye-object-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "opencv-contrib-python",
  "numpy",
  "pyntcore",
  "robotpy-wpimath",
  "ultralytics",
  "torch",
  "torchvision",
  "tqdm",
  "pillow",
  "filelock",
  "pygrabber",
  "comtypes",
  "pupil-apriltags",
  "flask",
  "flask-cors",
  "flask-socketio",
  "line_profiler",
  "onnxruntime",
  "maturin",
  "pydantic",
  "mypy",
  "psutil",
  "memryx==2.2.5; sys_platform == 'linux'",
]

[[tool.uv.index]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "memryx"
url = "https://developer.memryx.com/pip"
explicit = true

[tool.uv.sources]
memryx = { index = "memryx" }

[dependency-groups]
dev = [
  "pytest>=7.4",
  "pytest-anyio",
  "faker",
  "requests-mock",
]

[tool.uv]
required-environments = [
    "sys_platform == 'linux'"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-ra"
filterwarnings = [
    "error",
]
markers = [
    "hardware_skip: operation requires hardware or device access",
    "rust_optional: optional Rust extensions missing",
    "yolo_excluded: YOLO operations excluded from tests",
]
