// Shared state container for the pipeline creator UI.
export const creatorContext = {
    isInitialized: false,
    flowchartRenderer: null,
    backendRuntimeId: null,

    elements: {
        pipelineArea: null,
        pipelinePlaceholder: null,
        operationsList: null,
        runButton: null,
        pipelineSelect: null,
        pipelineCameraNote: null,
        newPipelineButton: null,
        deletePipelineButton: null,
        undoButton: null,
        redoButton: null,
        restartIndicator: null,
        flowchartCanvas: null,
        executionTimestepsList: null,
        executionSummaryContent: null,
        profilingDetailsOverlay: null,
        profilingDetailsModal: null,
        profilingDetailsBackdrop: null,
        profilingDetailsBody: null,
        profilingDetailsTitle: null,
        profilingDetailsCloseButton: null,
        profilingDetailsInfoButton: null,
        profilingDetailsAverageCheckbox: null,
    },
};
