name: "Dependabot Automerge - Action"

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  worker:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
     - name: Enable auto-merge for Dependabot PR
       uses: actions/github-script@v6
       with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const pr = context.payload.pull_request;
          if (!pr) throw new Error("No pull_request payload");
    
          await github.graphql(`
            mutation($prId: ID!) {
              enablePullRequestAutoMerge(input: {
                pullRequestId: $prId,
                mergeMethod: SQUASH
              }) {
                pullRequest {
                  autoMergeRequest {
                    enabledAt
                  }
                }
              }
            }
          `, {
            prId: pr.node_id
          });
